services:
  backend:
    build:
      context: ./backend/sam2
      dockerfile: Dockerfile
    container_name: medseg-backend
    ports:
      - "8000:8000"
    volumes:
      - backend-storage:/app/storage
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: medseg-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  backend-storage:
