services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "7263:5000"
    volumes:
      - ./storage:/opt/sam2/server/storage
    environment:
      - GUNICORN_WORKERS=1
      - GUNICORN_THREADS=2
      - SAM2_BUILD_CUDA=0
    reservations:
      devices:
        - driver: nvidia
          count: 1
          capabilities: [ gpu ]

  frontend:
    build:
      context: ../../frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE=http://localhost:7263
    ports:
      - "80:80"
    depends_on:
      - backend
