services:
  backend:
    image: sam2/backend
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "7263:5000"
    volumes:
      - ./storage:/opt/sam2/server/storage
    environment:
      - GUNICORN_WORKERS=1
      - GUNICORN_THREADS=2
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  frontend:
    image: sam2/frontend
    build:
      context: ../../frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE=http://localhost:7263
    ports:
      - "80:80"
    depends_on:
      - backend
